SuperUser.create(email: 'super@admin.com', password: 'password', password_confirmation: 'password')

Brand.create(name: 'AutoLab', address: 'Av. NQS # 70 - 16', telephone: '7429249',nit: '123456456')

BrandAdmin.create(email: 'admin@autolab.com', password: 'password', password_confirmation: 'password',brand_id:1)

CarExpert.create(email: 'car_expert@autolab.com', password: 'password', password_confirmation: 'password',brand_id:1)

Dispatcher.create(email: 'dispatcher@autolab.com', password: 'password', password_confirmation: 'password',brand_id:1)

QuestionCategory.create(name:"Motor",order_category: 1)
QuestionCategory.create(name:"Interior",order_category: 2)
QuestionCategory.create(name:"Exterior",order_category: 3)
QuestionCategory.create(name:"Parte baja",order_category: 4)
QuestionCategory.create(name:"Alineación y llantas",order_category: 5)
QuestionCategory.create(name:"Accesorios",order_category: 6)

CarType.new(name:"SUV").save!
CarType.new(name:"Hatchback").save!
CarType.new(name:"Sedan").save!

Question.create([
  { key: "paint_cond", text_query: "Condición de la pintura", question_category_id: 3, question_type: "range",order_question: 1, points: 40 },
  { key: "floors", text_query: "Tapetes", question_category_id: 2, question_type: "range", order_question: 1, points: 2 },
  { key: "carpet", text_query: "Alfombra", question_category_id: 2, question_type: "range", order_question: 2, points: 10 },
  { key: "cup_holders", text_query: "Portavasos", question_category_id: 2, question_type: "range", order_question: 3, points: 7 },
  { key: "upholstery", text_query: "Estado de tapicería", question_category_id: 2, question_type: "range", order_question: 4, points: 15 },
  { key: "electric_seats_state", text_query: "Estado asientos eléctricos", question_category_id: 2, question_type: "good_bad_na", order_question: 5, points: 10 },
  { key: "radio_function", text_query: "Funcionamiento de radio", question_category_id: 2, question_type: "range", order_question: 6, points: 10 },
  { key: "panel_buttons_state", text_query: "Estado botones del panel", question_category_id: 2, question_type: "range", order_question: 7, points: 10 },
  { key: "abnormal_odors", text_query: "Olores anormales", question_category_id: 2, question_type: "yes_or_no", order_question: 8, points: 8 },
  { key: "seatbelt_quantity", text_query: "Cantidad de cinturones de seguridad", question_category_id: 2, question_type: "text", order_question: 9, points: 0 },
  { key: "seatbelt_quality", text_query: "Estado de cinturones de seguridad", question_category_id: 2, question_type: "range", order_question: 10, points: 10 },
  { key: "computer_display_status", text_query: "Estado display computador", question_category_id: 2, question_type: "good_bad", order_question: 12, points: 15 },
  { key: "sunroof", text_query: "Sunroof", question_category_id: 2, question_type: "good_bad_na", order_question: 13, points: 9 },
  { key: "rearview_mirrors", text_query: "Retrovisores", question_category_id: 2, question_type: "range", order_question: 14, points: 5 },
  { key: "rearview_electric_function", text_query: "Funcionamiento retrovisores eléctricos", question_category_id: 2, question_type: "good_bad_na", order_question: 15, points: 8 },
  { key: "glove_compartment", text_query: "Guantera", question_category_id: 2, question_type: "range",order_question: 16, points: 8 },
  { key: "airbag_light_is_off", text_query: "Testigo airbags apagado", question_category_id: 2, question_type: "yes_no_na", order_question: 17, points: 20 },
  { key: "original_airbags", text_query: "Airbags Originales", question_category_id: 2, question_type: "yes_no_na", order_question: 11, points: 40 },
  { key: "number_of_airbags", text_query: "Número de airbags", question_category_id: 2, question_type: "text",order_question: 18, points: 0 },
  { key: "direction_wheel", text_query: "Volante de dirección", question_category_id: 2, question_type: "range",order_question: 19, points: 8 },
  { key: "direction_wheel_controls", text_query: "Funcionamiento de los controles del volante", question_category_id: 2, question_type: "good_bad_na", order_question: 20, points: 8 },
  { key: "central_blocking_system", text_query: "Bloqueo central", question_category_id: 2, question_type: "good_bad_na", order_question: 21, points: 8 },
  { key: "speakers", text_query: "Parlantes", question_category_id: 2, question_type: "yes_or_no", order_question: 22, points: 8 },
  { key: "pedals", text_query: "Pedales", question_category_id: 2, question_type: "range", order_question: 23, points: 7 },
  { key: "emergency_break", text_query: "Freno de emergencia", question_category_id: 2, question_type: "range", order_question: 24, points: 10 },
  { key: "ac", text_query: "Tiene A/C", question_category_id: 2, question_type: "yes_no_na", order_question: 25, points: 0 },
  { key: "ac_state", text_query: "Estado de A/C", question_category_id: 2, question_type: "good_bad_na", order_question: 26, points: 10 },
  { key: "panel_frame_state", text_query: "Estado de millaré", question_category_id: 2, question_type: "range", order_question: 27, points: 8 },
  { key: "interior_lights", text_query: "Luces interiores", question_category_id: 2, question_type: "good_bad", order_question: 28, points: 7 },
  { key: "frontal_lights_buttons", text_query: "Luces delanteras", question_category_id: 2, question_type: "yes_or_no", order_question: 29, points: 10 },
  { key: "back_lights_buttons", text_query: "Luces traseras", question_category_id: 2, question_type: "yes_or_no", order_question: 30, points: 10 },
  { key: "turn_frontal_lights_button", text_query: "Direccionales delanteras", question_category_id: 2, question_type: "yes_or_no", order_question: 36, points: 10 },
  { key: "turn_back_lights_button", text_query: "Direccionales traseras", question_category_id: 2, question_type: "yes_or_no", order_question: 31, points: 10 },
  { key: "turn_lights_on_rearview_mirrors", text_query: "Direccionales en retrovisores", question_category_id: 2, question_type: "yes_no_na", order_question: 32, points: 10 },
  { key: "plate_lights", text_query: "Luces de placas", question_category_id: 2, question_type: "yes_or_no", order_question: 33, points: 5 },
  { key: "door_handles", text_query: "Manillas de las puertas", question_category_id: 2, question_type: "yes_or_no", order_question: 34, points: 10 },
  { key: "parking_lights", text_query: "Luces de parqueo", question_category_id: 2, question_type: "yes_or_no", order_question: 35, points: 10 },
  { key: "left_headlight", text_query: "Farola delantera izquierda", question_category_id: 3, question_type: "range", order_question: 6, points: 10 },
  { key: "left_frontal_mudguard", text_query: "Guardafango delantero izquierdo", question_category_id: 3, question_type: "range", order_question: 2, points: 10 },
  { key: "front_left_door", text_query: "Puerta delantera izquierda", question_category_id: 3, question_type: "range", order_question: 3, points: 30 },
  { key: "welding_points_front_door_left", text_query: "Puntos de soldadura puerta delantera izquierda", question_category_id: 3, question_type: "good_bad", order_question: 4, points: 10 },
  { key: "front_left_door_sealing", text_query: "Sellado de puertas", question_category_id: 3, question_type: "good_bad", order_question: 5, points: 10 },
  { key: "front_left_tire_treading", text_query: "Labrado de las llantas", question_category_id: 4, question_type: "range", order_question: 6, points: 8 },
  { key: "front_left_tire_rim", text_query: "Estado de Rines o copas", question_category_id: 4, question_type: "range", order_question: 7, points: 8 },
  { key: "front_left_original_bolts", text_query: "Pernos originales", question_category_id: 4, question_type: "yes_or_no", order_question: 8, points: 8 },
  { key: "front_left_tire_alignment", text_query: "Posición de las llantas", question_category_id: 4, question_type: "good_bad", order_question: 9, points: 5 },
  { key: "front_left_shock_absorber", text_query: "Torres de amortiguadores delanteros", question_category_id: 4, question_type: "good_bad", order_question: 10, points: 8 },
  { key: "front_left_door_panel", text_query: "Panel interior puerta delantera izquierda (elevavidrios)", question_category_id: 3, question_type: "range", order_question: 7, points: 10 },
  { key: "front_left_window_control", text_query: "Estado elevavidrios izquierdo delantero", question_category_id: 3, question_type: "range", order_question: 8, points: 10 },
  { key: "left_rack", text_query: "Paral lateral izquierdo", question_category_id: 3, question_type: "good_bad", order_question: 9, points: 10 },
  { key: "left_original_sealings", text_query: "Sellantes originales en puertas", question_category_id: 3, question_type: "yes_or_no", order_question: 10, points: 10 },
  { key: "left_stirrup", text_query: "Estado estribo izquierdo", question_category_id: 3, question_type: "good_bad", order_question: 11, points: 10 },
  { key: "left_stoplight ", text_query: "Stop izquierdo", question_category_id: 2, question_type: "range", order_question: 37, points: 10 },
  { key: "left_back_mudguard", text_query: "Guardafango trasero izquierdo", question_category_id: 2, question_type: "range", order_question: 38, points: 8 },
  { key: "chassis_left_tip_rear", text_query: "Punta izquierda de chasis trasero", question_category_id: 2, question_type: "good_bad",order_question: 39, points: 30 },
  { key: "back_left_door", text_query: "Puerta trasera izquierda", question_category_id: 3, question_type: "range", order_question: 12, points: 30 },
  { key: "welding_points_back_door_left", text_query: "Puntos de soldadura puerta trasera izquierda", question_category_id: 3, question_type: "good_bad", order_question: 13, points: 10 },
  { key: "back_left_door_sealing", text_query: "Sellado de puertas", question_category_id: 3, question_type: "good_bad", order_question: 14, points: 10 },
  { key: "rear_left_tire_treading", text_query: "Labrado de las llantas", question_category_id: 4, question_type: "range", order_question: 1, points: 8 },
  { key: "rear_left_tire_rim", text_query: "Estado de Rines o copas", question_category_id: 4, question_type: "range", order_question: 2, points: 8 },
  { key: "rear_left_original_bolts", text_query: "Pernos originales", question_category_id: 4, question_type: "yes_or_no", order_question: 3, points: 8 },
  { key: "rear_left_tire_alignment", text_query: "Posición de las llantas", question_category_id: 4, question_type: "good_bad", order_question: 4, points: 5 },
  { key: "rear_left_shock_absorber", text_query: "Torres de amortiguadores traseros", question_category_id: 3, question_type: "good_bad", order_question: 15, points: 8 },
  { key: "rear_left_door_panel", text_query: "Panel puerta trasera izquierda", question_category_id: 3, question_type: "range", order_question: 16, points: 10 },
  { key: "rear_left_window_control", text_query: "Estado del elevavidrios izquierdo trasero", question_category_id: 3, question_type: "range", order_question: 17, points: 10 },
  { key: "rear_bumper", text_query: "Bumper trasero", question_category_id: 2, question_type: "range", order_question: 40, points: 20 },
  { key: "trunk_lid", text_query: "Puerta baúl", question_category_id: 2, question_type: "range", order_question: 41, points: 20 },
  { key: "rear_windshield", text_query: "Vidrio trasero", question_category_id: 2, question_type: "range", order_question: 42, points: 20 },
  { key: "gas_lid", text_query: "Puerta del tanque de combustible", question_category_id: 2, question_type: "range", order_question: 43, points: 10 },
  { key: "gas_cap_state", text_query: "Estado de la tapa del tanque de combustible", question_category_id: 3, question_type: "good_bad", order_question: 18, points: 10 },
  { key: "welding_points_trunk_door", text_query: "Puntos de soldadura baúl", question_category_id: 3, question_type: "good_bad", order_question: 19, points: 10 },
  { key: "crossing", text_query: "Traviesa (viga o panel posterior del vehículo)", question_category_id: 3, question_type: "range", order_question: 20, points: 10 },
  { key: "original_towing_hook", text_query: "Gancho de tiro original", question_category_id: 3, question_type: "yes_no_na", order_question: 21, points: 2 },
  { key: "rear_metal_dustpans", text_query: "Guardapolvos metálicos traseros", question_category_id: 3, question_type: "good_bad", order_question: 22, points: 10 },
  { key: "original_tire_kit", text_query: "Kit de despinche original", question_category_id: 4, question_type: "yes_no_na", order_question: 5, points: 1 },
  { key: "spare_tire", text_query: "Llanta de respuesto", question_category_id: 4, question_type: "yes_or_no", order_question: 11, points: 8 },
  { key: "trunk_original_sealing", text_query: "Sellantes originales en baúl", question_category_id: 3, question_type: "yes_or_no", order_question: 23, points: 10 },
  { key: "trunk_door_panel", text_query: "Panel puerta baúl", question_category_id: 3, question_type: "range", order_question: 24, points: 10 },
  { key: "right_stoplight ", text_query: "Stop derecho", question_category_id: 2, question_type: "range", order_question: 44, points: 10 },
  { key: "right_back_mudguard", text_query: "Guardafango trasero derecho", question_category_id: 2, question_type: "range", order_question: 45, points: 8 },
  { key: "chassis_right_tip_rear", text_query: "Punta derecha de chasis trasero", question_category_id: 2, question_type: "good_bad", order_question: 46, points: 30 },
  { key: "back_right_door", text_query: "Puerta trasera derecha", question_category_id: 3, question_type: "range", order_question: 25, points: 30 },
  { key: "welding_points_back_door_right", text_query: "Puntos de soldadura puerta trasera derecha", question_category_id: 3, question_type: "good_bad", order_question: 26, points: 10 },
  { key: "back_right_door_sealing", text_query: "Sellado de puertas", question_category_id: 3, question_type: "good_bad",order_question: 27, points: 10 },
  { key: "rear_right_tire_treading", text_query: "Labrado de las llantas", question_category_id: 4, question_type: "range",order_question: 12, points: 8 },
  { key: "rear_right_tire_rim", text_query: "Estado de Rines o copas", question_category_id: 4, question_type: "range",order_question: 13, points: 8 },
  { key: "rear_right_original_bolts", text_query: "Pernos originales", question_category_id: 4, question_type: "yes_or_no",order_question: 14, points: 8 },
  { key: "rear_right_tire_alignment", text_query: "Posición de las llantas", question_category_id: 4, question_type: "good_bad",order_question: 15, points: 5 },
  { key: "rear_right_shock_absorber", text_query: "Torres de amortiguadores traseros", question_category_id: 3, question_type: "good_bad",order_question: 28, points: 8 },
  { key: "rear_right_door_panel", text_query: "Panel puerta trasera derecha", question_category_id: 3, question_type: "range",order_question: 29, points: 10 },
  { key: "rear_right_window_control", text_query: "Estado del elevavidrios derecho trasero", question_category_id: 3, question_type: "range", order_question: 30, points: 10 },
  { key: "right_rack", text_query: "Paral lateral derecho", question_category_id: 3, question_type: "good_bad",order_question: 31, points: 10 },
  { key: "right_original_sealings", text_query: "Sellantes originales en puertas", question_category_id: 3, question_type: "yes_or_no",order_question: 32, points: 10 },
  { key: "right_stirrup", text_query: "Estado del estribo derecho", question_category_id: 3, question_type: "good_bad", order_question: 33, points: 10 },
  { key: "right_headlight", text_query: "Farola delantera derecha", question_category_id: 2, question_type: "range", order_question: 47, points: 10 },
  { key: "right_frontal_mudguard", text_query: "Guardafango delantero derecho", question_category_id: 2, question_type: "range", order_question: 48, points: 10 },
  { key: "front_right_door", text_query: "Puerta delantera derecha", question_category_id: 3, question_type: "range", order_question: 34, points: 30 },
  { key: "welding_points_front_door_right", text_query: "Puntos de soldadura puerta delantera derecha", question_category_id: 3, question_type: "good_bad", order_question: 35, points: 10 },
  { key: "front_right_door_sealing", text_query: "Sellado de puertas", question_category_id: 3, question_type: "good_bad", order_question: 36, points: 10 },
  { key: "front_right_tire_treading", text_query: "Labrado de las llantas", question_category_id: 4, question_type: "range", order_question: 16, points: 8 },
  { key: "front_right_tire_rim", text_query: "Estado de Rines o copas", question_category_id: 4, question_type: "range", order_question: 17, points: 8 },
  { key: "front_right_original_bolts", text_query: "Pernos originales", question_category_id: 4, question_type: "yes_or_no", order_question: 18, points: 8 },
  { key: "front_right_tire_alignment", text_query: "Posición de las llantas", question_category_id: 4, question_type: "good_bad", order_question: 19, points: 5 },
  { key: "front_right_shock_absorber", text_query: "Torres de amortiguadores delanteros", question_category_id: 3, question_type: "good_bad", order_question: 37, points: 8 },
  { key: "front_right_door_panel", text_query: "Panel interior puerta delantera derecha (elevavidrios)", question_category_id: 3, question_type: "range", order_question: 38, points: 10 },
  { key: "front_right_window_control", text_query: "Estado del elevavidrios derecho delantero", question_category_id: 3, question_type: "range", order_question: 39, points: 10 },
  { key: "front_windshield", text_query: "Vidrio panorámico delantero", question_category_id: 2, question_type: "range",order_question: 49, points: 30 },
  { key: "capot", text_query: "Capó", question_category_id: 2, question_type: "range",order_question: 50, points: 30 },
  { key: "frontal_bumper", text_query: "Bumper delantero", question_category_id: 2, question_type: "range",order_question: 51, points: 20 },
  { key: "fabric_stickers  ", text_query: "Calcomanías de fábrica", question_category_id: 2, question_type: "range", order_question: 52, points: 2 },
  { key: "screw_body_parts", text_query: "Tornillos de piezas de carrocería", question_category_id: 3, question_type: "good_bad", order_question: 40, points: 4 },
  { key: "chassis_right_tip_front", text_query: "Punta derecha de chasis delantero", question_category_id: 3, question_type: "good_bad", order_question: 41, points: 30 },
  { key: "chassis_left_tip_front", text_query: "Punta izquierda de chasis delantero", question_category_id: 3, question_type: "good_bad", order_question: 42, points: 30 },
  { key: "front_metal_dustpans", text_query: "Guardapolvos metálicos delanteros", question_category_id: 3, question_type: "good_bad", order_question: 43, points: 10 },
  { key: "engine_original_sealing", text_query: "Sellantes originales en motor", question_category_id: 3, question_type: "yes_or_no", order_question: 44, points: 10 },
  { key: "hoses", text_query: "Mangueras", question_category_id: 3, question_type: "range",order_question: 45, points: 10 },
  { key: "alternator_strap", text_query: "Correa de accesorios", question_category_id: 3, question_type: "range", order_question: 46, points: 10 },
  { key: "timing_belt", text_query: "Correa de repartición", question_category_id: 3, question_type: "range", order_question: 47, points: 10 },
  { key: "fluid_level", text_query: "nivel de fluidos", question_category_id: 3, question_type: "range", order_question: 48, points: 4 },
  { key: "engine_sludge", text_query: "Lodos del motor", question_category_id: 3, question_type: "yes_or_no", order_question: 49, points: 40, },
  { key: "turbo_state", text_query: "Estado del turbo", question_category_id: 3, question_type: "good_bad_na", order_question: 50, points: 10, },
  { key: "immediate_startup", text_query: "Encendido inmediato", question_category_id: 1, question_type: "good_bad", order_question: 2, points: 55 },
  { key: "on_warm_up", text_query: "Durante calentamiento", question_category_id: 1, question_type: "range", order_question: 1, points: 10 },
  { key: "tachometer", text_query: "Funcionamiento del tacómetro", question_category_id: 1, question_type: "good_bad", order_question: 3, points: 15 },
  { key: "abnormal_noises_on_engine", text_query: "Ruidos anormales en motor", question_category_id: 1, question_type: "yes_or_no", order_question: 5, points: 55 },
  { key: "engine_vibration", text_query: "Vibración del motor", question_category_id: 1, question_type: "yes_or_no", order_question: 4, points: 55 },
  { key: "exhaust_system_status", text_query: "Estado sistema de escape", question_category_id: 8, question_type: "range", order_question: 5, points: 15 },
  { key: "fluid_leaks", text_query: "Fuga de fluidos", question_category_id: 1, question_type: "yes_or_no", order_question: 6, points: 30 },
  { key: "top", text_query: "Techo", question_category_id: 2, question_type: "range", order_question: 53, points: 10 },
  { key: "body_floor", text_query: "Piso carrocería", question_category_id: 3, question_type: "range", order_question: 51, points: 8 },
  { key: "wiring_state", text_query: "Estado de cables eléctricos", question_category_id: 1, question_type: "range", order_question: 7, points: 10 },
  { key: "exhaust_tubing_state", text_query: "Estado tuberías", question_category_id: 1, question_type: "range", order_question: 8, points: 10 },
  { key: "dustpan_state", text_query: "Estado de guardapolvos", question_category_id: 1, question_type: "range", order_question: 9, points: 10 },
  { key: "steel_cable_state", text_query: "Estado de guayas", question_category_id: 1, question_type: "range", order_question: 10, points: 10 },
  { key: "clutch", text_query: "Funcionamiento de embrague", question_category_id: 5, question_type: "range", order_question: 1, points: 55 },
  { key: "gearbox", text_query: "Funcionamiento de caja de cambios", question_category_id: 5, question_type: "good_bad", order_question: 2, points: 55 },
  { key: "gearbox_handle_operation", text_query: "Operación palanca de cambios", question_category_id: 5, question_type: "good_bad", order_question: 3, points: 20 },
  { key: "gearbox_4_4_control", text_query: "Operación palanca ó control 4x4", question_category_id: 5, question_type: "yes_no_na", order_question: 4, points: 20 },
  { key: "dif_function", text_query: "Funcionamiento de diferencial", question_category_id: 5, question_type: "good_bad", order_question: 5, points: 55 },
  { key: "auto_dif_hook", text_query: "Enganche diferencial automático", question_category_id: 5, question_type: "good_bad", order_question: 6, points: 10 },
  { key: "front_axle", text_query: "Estado de eje delantero", question_category_id: 5, question_type: "range", order_question: 8, points: 55 },
  { key: "rear_axle", text_query: "Estado de eje trasero", question_category_id: 5, question_type: "range", order_question: 9, points: 55 },
  { key: "suspension", text_query: "Estado de suspensión", question_category_id: 5, question_type: "range", order_question: 7, points: 55 },
  { key: "startup_function", text_query: "Funcionamiente del arranque", question_category_id: 1, question_type: "good_bad", order_question: 11, points: 55 },
  { key: "transmission_noises", text_query: "Ruidos en transmisión", question_category_id: 1, question_type: "yes_or_no", order_question: 12, points: 55 },
  { key: "gearbox_noises", text_query: "Ruidos en caja", question_category_id: 1, question_type: "yes_or_no", order_question: 13, points: 55 },
  { key: "wheel_noises", text_query: "Ruidos en las llantas", question_category_id: 1, question_type: "yes_or_no", order_question: 14, points: 55 },
  { key: "steering_wheel", text_query: "Operación del volante de extremo a extremo", question_category_id: 1, question_type: "range", order_question: 15, points: 20 },
  { key: "steering_system_on_hot_engine_state", text_query: "Funcionamiento del sistema de dirección del motor", question_category_id: 1, question_type: "range", order_question: 16, points: 20 },
  { key: "turbo_hook", text_query: "Enganche del turbo", question_category_id: 1, question_type: "good_bad_na", order_question: 17, points: 10 },
  { key: "non_centered_driving_wheel", text_query: "Volante descentrado", question_category_id: 1, question_type: "yes_or_no", order_question: 18, points: 55 }
])
